//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoIntegradoVerde.RecursosLocalizables {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringRecursos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringRecursos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProyectoIntegradoVerde.RecursosLocalizables.StringRecursos", typeof(StringRecursos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar.
        /// </summary>
        internal static string adTar_btnCerrar {
            get {
                return ResourceManager.GetString("adTar_btnCerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar.
        /// </summary>
        internal static string adTar_btnEnviar {
            get {
                return ResourceManager.GetString("adTar_btnEnviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Tarea.
        /// </summary>
        internal static string adTar_lblAgregarT {
            get {
                return ResourceManager.GetString("adTar_lblAgregarT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción:.
        /// </summary>
        internal static string adTar_lblDesc {
            get {
                return ResourceManager.GetString("adTar_lblDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Límite:.
        /// </summary>
        internal static string adTar_lblFLimite {
            get {
                return ResourceManager.GetString("adTar_lblFLimite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Punto:.
        /// </summary>
        internal static string adTar_lblPuntos {
            get {
                return ResourceManager.GetString("adTar_lblPuntos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Título:.
        /// </summary>
        internal static string adTar_lblTitulo {
            get {
                return ResourceManager.GetString("adTar_lblTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Tarea.
        /// </summary>
        internal static string adTar_title {
            get {
                return ResourceManager.GetString("adTar_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Has olvidado tu contraseña?.
        /// </summary>
        internal static string contOlv {
            get {
                return ResourceManager.GetString("contOlv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Reunión.
        /// </summary>
        internal static string crun_btnCrearReunion {
            get {
                return ResourceManager.GetString("crun_btnCrearReunion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargos asociados:.
        /// </summary>
        internal static string crun_lblCargos {
            get {
                return ResourceManager.GetString("crun_lblCargos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Creación de Reunión.
        /// </summary>
        internal static string crun_lblCrearReunion {
            get {
                return ResourceManager.GetString("crun_lblCrearReunion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de la Reunión.
        /// </summary>
        internal static string crun_lblFechaReunion {
            get {
                return ResourceManager.GetString("crun_lblFechaReunion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hora de la Reunión.
        /// </summary>
        internal static string crun_lblHoraReunion {
            get {
                return ResourceManager.GetString("crun_lblHoraReunion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción:.
        /// </summary>
        internal static string crun_lblRDesc {
            get {
                return ResourceManager.GetString("crun_lblRDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre:.
        /// </summary>
        internal static string crun_lblRNombre {
            get {
                return ResourceManager.GetString("crun_lblRNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CrearReunion.
        /// </summary>
        internal static string crun_title {
            get {
                return ResourceManager.GetString("crun_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        internal static string dat_btnCerrar {
            get {
                return ResourceManager.GetString("dat_btnCerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargo.
        /// </summary>
        internal static string dat_lblCargo {
            get {
                return ResourceManager.GetString("dat_lblCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de empleado.
        /// </summary>
        internal static string dat_lblCode {
            get {
                return ResourceManager.GetString("dat_lblCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalles del Usuario.
        /// </summary>
        internal static string dat_lblDetalles {
            get {
                return ResourceManager.GetString("dat_lblDetalles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de Identificacion.
        /// </summary>
        internal static string dat_lblNif {
            get {
                return ResourceManager.GetString("dat_lblNif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string dat_lblNombre {
            get {
                return ResourceManager.GetString("dat_lblNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puntos.
        /// </summary>
        internal static string dat_lblPuntos {
            get {
                return ResourceManager.GetString("dat_lblPuntos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar.
        /// </summary>
        internal static string fun_btnActualizarReuniones {
            get {
                return ResourceManager.GetString("fun_btnActualizarReuniones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Reunión.
        /// </summary>
        internal static string fun_btnCrearReunion {
            get {
                return ResourceManager.GetString("fun_btnCrearReunion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear tarea.
        /// </summary>
        internal static string fun_btnCrearTarea {
            get {
                return ResourceManager.GetString("fun_btnCrearTarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar.
        /// </summary>
        internal static string fun_btnEnviar {
            get {
                return ResourceManager.GetString("fun_btnEnviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limpiar campos.
        /// </summary>
        internal static string fun_btnLimpiar {
            get {
                return ResourceManager.GetString("fun_btnLimpiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID.
        /// </summary>
        internal static string fun_dgv1_1 {
            get {
                return ResourceManager.GetString("fun_dgv1-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Titulo.
        /// </summary>
        internal static string fun_dgv1_2 {
            get {
                return ResourceManager.GetString("fun_dgv1-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F.Publicación.
        /// </summary>
        internal static string fun_dgv1_3 {
            get {
                return ResourceManager.GetString("fun_dgv1-3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puntos.
        /// </summary>
        internal static string fun_dgv1_4 {
            get {
                return ResourceManager.GetString("fun_dgv1-4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F.Límite.
        /// </summary>
        internal static string fun_dgv1_5 {
            get {
                return ResourceManager.GetString("fun_dgv1-5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string fun_dgv2_1 {
            get {
                return ResourceManager.GetString("fun_dgv2-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        internal static string fun_dgv2_2 {
            get {
                return ResourceManager.GetString("fun_dgv2-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        internal static string fun_dgv2_3 {
            get {
                return ResourceManager.GetString("fun_dgv2-3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asunto.
        /// </summary>
        internal static string fun_dgv3_1 {
            get {
                return ResourceManager.GetString("fun_dgv3-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cuerpo.
        /// </summary>
        internal static string fun_dgv3_2 {
            get {
                return ResourceManager.GetString("fun_dgv3-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remitente.
        /// </summary>
        internal static string fun_dgv3_3 {
            get {
                return ResourceManager.GetString("fun_dgv3-3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        internal static string fun_dgv3_4 {
            get {
                return ResourceManager.GetString("fun_dgv3-4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string fun_dgv4_1 {
            get {
                return ResourceManager.GetString("fun_dgv4-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coste.
        /// </summary>
        internal static string fun_dgv4_2 {
            get {
                return ResourceManager.GetString("fun_dgv4-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        internal static string fun_dgv4_3 {
            get {
                return ResourceManager.GetString("fun_dgv4-3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        internal static string fun_dgv4_4 {
            get {
                return ResourceManager.GetString("fun_dgv4-4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asunto:.
        /// </summary>
        internal static string fun_lblAsunt {
            get {
                return ResourceManager.GetString("fun_lblAsunt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Doble click para comprar un producto.
        /// </summary>
        internal static string fun_lblComProd {
            get {
                return ResourceManager.GetString("fun_lblComProd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Destinatario:.
        /// </summary>
        internal static string fun_lblDestin {
            get {
                return ResourceManager.GetString("fun_lblDestin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puntos disponibles:.
        /// </summary>
        internal static string fun_lblDispo {
            get {
                return ResourceManager.GetString("fun_lblDispo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Doble click para asignarte una tarea.
        /// </summary>
        internal static string fun_lblDobleClick {
            get {
                return ResourceManager.GetString("fun_lblDobleClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Doble click para completar una tarea.
        /// </summary>
        internal static string fun_lblDobleClick2 {
            get {
                return ResourceManager.GetString("fun_lblDobleClick2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Doble click para leer el cuerpo del correo seleccionado.
        /// </summary>
        internal static string fun_lblEmail {
            get {
                return ResourceManager.GetString("fun_lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tareas disponibles.
        /// </summary>
        internal static string fun_lblInfo1 {
            get {
                return ResourceManager.GetString("fun_lblInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tareas pendientes.
        /// </summary>
        internal static string fun_lblInfo2 {
            get {
                return ResourceManager.GetString("fun_lblInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Funcionalidades.
        /// </summary>
        internal static string fun_prinTitle {
            get {
                return ResourceManager.GetString("fun_prinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tareas.
        /// </summary>
        internal static string fun_tc_1 {
            get {
                return ResourceManager.GetString("fun_tc-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calendario.
        /// </summary>
        internal static string fun_tc_2 {
            get {
                return ResourceManager.GetString("fun_tc-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reuniones.
        /// </summary>
        internal static string fun_tc_3 {
            get {
                return ResourceManager.GetString("fun_tc-3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo.
        /// </summary>
        internal static string fun_tc_4 {
            get {
                return ResourceManager.GetString("fun_tc-4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tienda.
        /// </summary>
        internal static string fun_tc_5 {
            get {
                return ResourceManager.GetString("fun_tc-5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Funcionalidades.
        /// </summary>
        internal static string fun_title {
            get {
                return ResourceManager.GetString("fun_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ESP.
        /// </summary>
        internal static string lang {
            get {
                return ResourceManager.GetString("lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        internal static string logIn {
            get {
                return ResourceManager.GetString("logIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notificar a un administrador..
        /// </summary>
        internal static string notiAd {
            get {
                return ResourceManager.GetString("notiAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        internal static string pan_adbtnAgregar {
            get {
                return ResourceManager.GetString("pan_adbtnAgregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargar imagen.
        /// </summary>
        internal static string pan_adbtnCargar {
            get {
                return ResourceManager.GetString("pan_adbtnCargar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar.
        /// </summary>
        internal static string pan_adbtnCerrar {
            get {
                return ResourceManager.GetString("pan_adbtnCerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar.
        /// </summary>
        internal static string pan_adbtnModificar {
            get {
                return ResourceManager.GetString("pan_adbtnModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deshabilitado:.
        /// </summary>
        internal static string pan_adcheckDeshab {
            get {
                return ResourceManager.GetString("pan_adcheckDeshab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string pan_addtg_1 {
            get {
                return ResourceManager.GetString("pan_addtg_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F.nacimiento.
        /// </summary>
        internal static string pan_addtg_2 {
            get {
                return ResourceManager.GetString("pan_addtg_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargo.
        /// </summary>
        internal static string pan_addtg_3 {
            get {
                return ResourceManager.GetString("pan_addtg_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puntos.
        /// </summary>
        internal static string pan_addtg_4 {
            get {
                return ResourceManager.GetString("pan_addtg_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo.
        /// </summary>
        internal static string pan_addtg_5 {
            get {
                return ResourceManager.GetString("pan_addtg_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string pan_addtg_6 {
            get {
                return ResourceManager.GetString("pan_addtg_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borrado.
        /// </summary>
        internal static string pan_addtg_7 {
            get {
                return ResourceManager.GetString("pan_addtg_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargo:.
        /// </summary>
        internal static string pan_adlblCargo {
            get {
                return ResourceManager.GetString("pan_adlblCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo:.
        /// </summary>
        internal static string pan_adlblCorr {
            get {
                return ResourceManager.GetString("pan_adlblCorr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F.Nacimiento.
        /// </summary>
        internal static string pan_adlblfech {
            get {
                return ResourceManager.GetString("pan_adlblfech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Foto:.
        /// </summary>
        internal static string pan_adlblFoto {
            get {
                return ResourceManager.GetString("pan_adlblFoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID(Antes del cambio).
        /// </summary>
        internal static string pan_adlblIdAntes {
            get {
                return ResourceManager.GetString("pan_adlblIdAntes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string pan_adlblNom {
            get {
                return ResourceManager.GetString("pan_adlblNom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string pan_adlblPassw {
            get {
                return ResourceManager.GetString("pan_adlblPassw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puntos:.
        /// </summary>
        internal static string pan_adlblPunt {
            get {
                return ResourceManager.GetString("pan_adlblPunt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Panel de administración.
        /// </summary>
        internal static string pan_adTitulo {
            get {
                return ResourceManager.GetString("pan_adTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string passwd {
            get {
                return ResourceManager.GetString("passwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar.
        /// </summary>
        internal static string regBtnClose {
            get {
                return ResourceManager.GetString("regBtnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar.
        /// </summary>
        internal static string regBtnReg {
            get {
                return ResourceManager.GetString("regBtnReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargar.
        /// </summary>
        internal static string regCargar {
            get {
                return ResourceManager.GetString("regCargar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargo:.
        /// </summary>
        internal static string regCargo {
            get {
                return ResourceManager.GetString("regCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña:.
        /// </summary>
        internal static string regClave {
            get {
                return ResourceManager.GetString("regClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mostrar contraseña.
        /// </summary>
        internal static string regMostContra {
            get {
                return ResourceManager.GetString("regMostContra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha:.
        /// </summary>
        internal static string regNaci {
            get {
                return ResourceManager.GetString("regNaci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre:.
        /// </summary>
        internal static string regNombre {
            get {
                return ResourceManager.GetString("regNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro de usuario.
        /// </summary>
        internal static string regTitle {
            get {
                return ResourceManager.GetString("regTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar Usuario.
        /// </summary>
        internal static string regUsu {
            get {
                return ResourceManager.GetString("regUsu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notificar Error.
        /// </summary>
        internal static string sop_tapcontrol1 {
            get {
                return ResourceManager.GetString("sop_tapcontrol1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recuperar contraseña.
        /// </summary>
        internal static string sop_tapcontrol2 {
            get {
                return ResourceManager.GetString("sop_tapcontrol2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Soporte.
        /// </summary>
        internal static string sop_title {
            get {
                return ResourceManager.GetString("sop_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar.
        /// </summary>
        internal static string sopbtnEnviar {
            get {
                return ResourceManager.GetString("sopbtnEnviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Un administrador contactara con usted con su nueva contraseña..
        /// </summary>
        internal static string sopBtnENvin2 {
            get {
                return ResourceManager.GetString("sopBtnENvin2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar informe.
        /// </summary>
        internal static string sopbtnEnvInf1 {
            get {
                return ResourceManager.GetString("sopbtnEnvInf1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, describa el error de la manera más precisa posible:.
        /// </summary>
        internal static string sopTitle {
            get {
                return ResourceManager.GetString("sopTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inserte el correo electrónico asociado a su cuenta:.
        /// </summary>
        internal static string sopTitle2 {
            get {
                return ResourceManager.GetString("sopTitle2", resourceCulture);
            }
        }
    }
}
